ecommerce/payment/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views

app_name = 'payment'

urlpatterns = [
    path(_('process/'), views.payment_process, name='process'),
    path(_('completed/'), views.payment_completed, name='completed'),
    path(_('canceled/'), views.payment_canceled, name='canceled'),
]

ecommerce/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from payment import webhooks

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)

urlpatterns += [
    path('payment/webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/payment/models.py
from django.db import models

# Create your models here.

ecommerce/payment/views.py
from decimal import Decimal
import stripe
from django.conf import settings
from django.shortcuts import render, redirect, reverse,\
                             get_object_or_404
from orders.models import Order


# create the Stripe instance
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        success_url = request.build_absolute_uri(
                        reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(
                        reverse('payment:canceled'))

        # Stripe checkout session data
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }
        # add order items to the Stripe checkout session
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'usd',
                    'product_data': {
                        'name': item.product.name,
                    },
                },
                'quantity': item.quantity,
            })

        # Stripe coupon
        if order.coupon:
            stripe_coupon = stripe.Coupon.create(
                                name=order.coupon.code,
                                percent_off=order.discount,
                                duration='once')
            session_data['discounts'] = [{
                'coupon': stripe_coupon.id
            }]

        # create Stripe checkout session
        session = stripe.checkout.Session.create(**session_data)

        # redirect to Stripe payment form
        return redirect(session.url, code=303)

    else:
        return render(request, 'payment/process.html', locals())


def payment_completed(request):
    return render(request, 'payment/completed.html')


def payment_canceled(request):
    return render(request, 'payment/canceled.html')

ecommerce/payment/templates/payment/canceled.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block title %}{% trans "Payment canceled" %}{% endblock %}

{% block content %}
  <h1>{% trans "Your payment has not been processed" %}</h1>
  <p>{% trans "There was a problem processing your payment." %}</p>
{% endblock %}

ecommerce/payment/templates/payment/completed.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block title %}{% trans "Payment successful" %}{% endblock %}

{% block content %}
  <h1>{% trans "Your payment was successful" %}</h1>
  <p>{% trans "Your payment has been processed successfully." %}</p>
{% endblock %}

ecommerce/payment/templates/payment/process.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Pay your order" %}{% endblock %}

{% block content %}
 <!--
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ],
  }
  ```
-->
<div class="bg-gray-50">
  <!--
    Mobile menu

    Off-canvas menu for mobile, show/hide based on off-canvas menu state.
  -->


  <main class="mx-auto max-w-2xl pb-24 pt-8 sm:px-6 sm:pt-16 lg:max-w-7xl lg:px-8">
    <div class="space-y-2 px-4 sm:flex sm:items-baseline sm:justify-between sm:space-y-0 sm:px-0">
      <div class="flex sm:items-baseline sm:space-x-4">
        <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">Order #54879</h1>
      </div>
      <p class="text-sm text-gray-600">Order placed <time datetime="2021-03-22" class="font-medium text-gray-900">March 22, 2021</time></p>
    </div>

    <!-- Products -->
    <section aria-labelledby="products-heading" class="mt-6">
      <h2 id="products-heading" class="sr-only">Products purchased</h2>

      <div class="space-y-8">
        <div class="border-b border-t border-gray-200 bg-white shadow-sm sm:rounded-lg sm:border">
          {% for item in order.items.all %}
          <div class="px-4 py-6 sm:px-6 lg:grid lg:grid-cols-12 lg:gap-x-8 lg:p-8">
            <div class="sm:flex lg:col-span-7">
              <img src="{% if item.product.image %}{{ item.product.image.url }}
              {% else %}{% static "img/no_image.png" %}{% endif %}" alt="Insulated bottle with white base and black snap lid." class="aspect-square w-full shrink-0 rounded-lg object-cover sm:size-40">

              <div class="mt-6 sm:ml-6 sm:mt-0">
                <h3 class="text-base font-medium text-gray-900">
                  <a href="#">{{ item.product.name }}
                    <p class="mt-2 text-sm font-medium text-gray-900">X {{ item.quantity }}</p>
                  </a>
                 
                </h3>
                <p class="mt-2 text-sm font-medium text-gray-900">${{ item.get_cost }}</p>
                <p class="mt-3 text-sm text-gray-500">{{ item.description }}</p>
              </div>
            </div>

            <div class="mt-6 lg:col-span-5 lg:mt-0">
              <dl class="grid grid-cols-2 gap-x-6 text-sm">
                <div>
                  <dt class="font-medium text-gray-900">Delivery address</dt>
                  <dd class="mt-3 text-gray-500">
                    <span class="block">{{ order.address}}</span>
                  </dd>
                </div>
                <div>
                  <dt class="font-medium text-gray-900">Shipping updates</dt>
                  <dd class="mt-3 space-y-3 text-gray-500">
                    <p>f•••@example.com</p>
                    <p>1•••••••••40</p>
                    <button type="button" class="font-medium text-indigo-600 hover:text-indigo-500">Edit</button>
                  </dd>
                </div>
              </dl>
            </div>
          </div>

          {% endfor %}
        </div>

        <!-- More products... -->
      </div>
    </section>

    <!-- Billing -->
    <section aria-labelledby="summary-heading" class="mt-16">
      <h2 id="summary-heading" class="sr-only">Billing Summary</h2>

      <div class="bg-gray-100 px-4 py-6 sm:rounded-lg sm:px-6 lg:grid lg:grid-cols-12 lg:gap-x-8 lg:px-8 lg:py-8">
        <dl class="grid grid-cols-2 gap-6 text-sm sm:grid-cols-2 md:gap-x-8 lg:col-span-7">
          <div>
            <dt class="font-medium text-gray-900">Billing address</dt>
            <dd class="mt-3 text-gray-500">
              <span class="block">{{ order.address}}</span>
            </dd>
          </div>
          <form action="{% url "payment:process" %}" method="post">
            <input type="submit" value="Pay ${{ order.get_total_cost|floatformat:2 }}" class="mt-6 w-full rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
            {% csrf_token %}
          </form>
        </dl>


        <dl class="mt-8 divide-y divide-gray-200 text-sm lg:col-span-5 lg:mt-0">
          <div class="flex items-center justify-between pb-4">
            <dt class="text-gray-600">{% trans "Subtotal" %}</dt>
            <dd class="font-medium text-gray-900">${{ order.get_total_cost_before_discount|floatformat:2 }}</dd>
          </div>
          {% if order.coupon %}
          <div class="flex items-center justify-between py-4">
            <dt class="text-gray-600">Discount</dt>
            <dd class="font-medium text-gray-900">- ${{ order.get_discount|floatformat:2 }}</dd>
          </div>
          {% endif %}
          <div class="flex items-center justify-between pt-4">
            <dt class="font-medium text-gray-900">{% trans "Total" %}</dt>
            <dd class="font-medium text-indigo-600">${{ order.get_total_cost|floatformat:2 }}</dd>
          </div>
          
        </dl>
      </div>
    </section>
  </main>

  
</div>

{% endblock %}